### ISSUE TITLE
Prepare for release and going out of beta

### ISSUE THREAD

**Issue by scrumpypoker** [scrumpypoker/i18n#10]
We're thrilled to announce that the application is finally gone [out of beta version](https://scrumpy.poker/2020/09/26/jira-automation-integration-in-release-sep-27-2020/)! Thank you all for your support and submitting translation requests!

Some of the strings were missing, because they were part of some unstable features. Now the product is reaching its release milestone and the missing texts are added. We apologize for adding those texts a bit late, we just didn't want anyone to spend effort in vain to translate something that is a subject for a change.

We also apologize for keeping quiet and not accepting your PRs since we had to first finalize the most important product features first and avoid bothering you with asking for small updates.

It is not expected to have more texts soon or maybe some very minor changes. The [latest release notes](https://scrumpy.poker/2020/09/05/micro-and-mini-poker-in-release-sep-5-2020) of the out-of-beta release might contain some information that will help with the translation. This version was not released on September 5th, but will be release the week after.

We'd be very grateful if you submit the changes to your translation files. We really value your help!

@CaiqueCoelho
@AmusedArg
@lablum
@thedigitalproblemsolver
@pmoe
@RaSiel93

**Comment by CaiqueCoelho** [comment]
@scrumpypoker new PR in #12 :1st_place_medal:

**Comment by scrumpypoker** [comment]
@CaiqueCoelho Deployed pt_BR on production, thanks for the PR!

**Comment by scrumpypoker** [comment]
To make your contributions easier we've implemented a new feature that allows you to immediately test the translation in the production application. Please check the project description or the [latest release](https://scrumpy.poker/2020/09/20/gitlab-sorting-and-voting-improvements-in-release-sep-20-2020/) notes for more information.
Certainly if something doesn't work as expected or you'd like to get some improvement don't hesitate to contact us! Thank you very much for your help!

**Comment by scrumpypoker** [comment]
@thedigitalproblemsolver the Dutch translation is [now live](https://scrumpy.poker/2020/11/01/averaging-technique-in-release-01-nov-2020/). Thank you very much for your contribution! With this we'll be closing this ticket, the milestone has been successfully reached. We're not beta anymore, looking forward the next big milestone!
